/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Human.gltf 
Author: zeroran (https://sketchfab.com/zeroran)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/anatomy-basemesh-human-male-body-model-sculpture-8c49edd7e9bd4dc7ba3c4b493b00d7ab
Title: Anatomy Basemesh Human Male Body Model Sculpture
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Human.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group scale={100}>
            <mesh geometry={nodes['60Wip_(null)_0'].geometry} material={materials['null']} />
            <mesh geometry={nodes['60Wip_(null)_0_1'].geometry} material={materials['null']} />
            <mesh geometry={nodes['60Wip_(null)_0_2'].geometry} material={materials['null']} />
            <mesh geometry={nodes['60Wip_(null)_0_3'].geometry} material={materials['null']} />
            <mesh geometry={nodes['60Wip_(null)_0_4'].geometry} material={materials['null']} />
            <mesh geometry={nodes['60Wip_(null)_0_5'].geometry} material={materials['null']} />
            <mesh geometry={nodes['60Wip_(null)_0_6'].geometry} material={materials['null']} />
            <mesh geometry={nodes['60Wip_(null)_0_7'].geometry} material={materials['null']} />
            <mesh geometry={nodes['60Wip_(null)_0_8'].geometry} material={materials['null']} />
            <mesh geometry={nodes['60Wip_(null)_0_9'].geometry} material={materials['null']} />
            <mesh geometry={nodes['60Wip_(null)_0_10'].geometry} material={materials['null']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Human.gltf')
